[project]
name = "project"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = ["rich"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
